# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: yourdockerhubusername/backend:tag
#         ports:
#         - containerPort: 5400
#         env:
#         - name: MONGODB_URI
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: uri
